"""add submission feedback

Revision ID: 1f60a205ee2d
Revises: 2a3e791f3542
Create Date: 2026-08-10 20:30:43.994664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f60a205ee2d'
down_revision: Union[str, Sequence[str], None] = '2a3e791f3542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('feedback', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'feedback')
    # ### end Alembic commands ###
