"""fix school_class table name

Revision ID: 20548f2db591
Revises: da083ff707e1
Create Date: 2026-08-08 12:21:48.577146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20548f2db591'
down_revision: Union[str, Sequence[str], None] = 'da083ff707e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_school_class_name', 'school_classes', ['school_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_school_class_name', 'school_classes', type_='unique')
    # ### end Alembic commands ###
