"""add assignment table

Revision ID: 417c6a446812
Revises: cc25cb9dbdd7
Create Date: 2026-08-08 18:10:31.027003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '417c6a446812'
down_revision: Union[str, Sequence[str], None] = 'cc25cb9dbdd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('teacher_classes_class_id_fkey'), 'teacher_classes', type_='foreignkey')
    op.drop_constraint(op.f('teacher_classes_teacher_id_fkey'), 'teacher_classes', type_='foreignkey')
    op.create_foreign_key(None, 'teacher_classes', 'school_classes', ['class_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'teacher_classes', 'users', ['teacher_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher_classes', type_='foreignkey')
    op.drop_constraint(None, 'teacher_classes', type_='foreignkey')
    op.create_foreign_key(op.f('teacher_classes_teacher_id_fkey'), 'teacher_classes', 'users', ['teacher_id'], ['id'])
    op.create_foreign_key(op.f('teacher_classes_class_id_fkey'), 'teacher_classes', 'school_classes', ['class_id'], ['id'])
    # ### end Alembic commands ###
