"""add school_id to users

Revision ID: 73d816bc6214
Revises: 4f16e4d45fd1
Create Date: 2026-08-08 09:52:29.013379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73d816bc6214'
down_revision: Union[str, Sequence[str], None] = '4f16e4d45fd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('school_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'schools', ['school_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'school_id')
    # ### end Alembic commands ###
