"""add assignment status

Revision ID: ea3820c7014f
Revises: 463319fd4c4f
Create Date: 2026-08-08 21:36:32.611763

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ea3820c7014f"
down_revision: Union[str, Sequence[str], None] = "463319fd4c4f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    assignment_status = sa.Enum(
        "DRAFT",
        "REVIEW_REQUIRED",
        "APPROVED",
        "ACTIVE",
        "COMPLETED",
        "CANCELLED",
        name="assignmentstatus",
    )
    assignment_status.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "assignments",
        sa.Column(
            "status",
            assignment_status,
            nullable=False,
            server_default="DRAFT",
        ),
    )
    op.alter_column("assignments", "status", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assignments", "status")

    assignment_status = sa.Enum(
        "DRAFT",
        "REVIEW_REQUIRED",
        "APPROVED",
        "ACTIVE",
        "COMPLETED",
        "CANCELLED",
        name="assignmentstatus",
    )
    assignment_status.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
