from enum import Enum


class ChatConversationStatus(str, Enum):
    NEW = "NEW"
    PROCESSING = "PROCESSING"
    CLARIFICATION_REQUIRED = "CLARIFICATION_REQUIRED"
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    APPROVED = "APPROVED"
    EXECUTING = "EXECUTING"
    COMPLETED = "COMPLETED"
    REJECTED = "REJECTED"
    FAILED = "FAILED"
